name = "simple-chat"
main = "worker.js"
compatibility_date = "2025-07-08"
account_id = "d34805ac74c21605bf55901c503f385f"

[[kv_namespaces]]
binding = "KV_CHAT"
id = "d5a91d4b34a14d3dba9933adc9f0768e"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]